name: Build
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build docker image
      run: make docker-build
    - name: Run tests
      run: make docker-runtest-all
    - name: Pylint action
      uses: gabriel-milan/action-pylint@v1
      with:
        # GitHub token
        GITHUB_TOKEN: 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
        # Path of files
        path: Mayan-EDMS/mayan/apps/permissions/views.py
        # If true, the action will fail if pylint finds errors (default is true)
        fail: true
        # If true, the action will send a PR message if pylint finds errors (default is true)
        pr-message: true
